language: node_js
node_js:
  - 12

services:
  - docker

branches:
  only:
    - master

  #Pre-testing installs
install:
  - npm install ionic -g
  - npm install
  - ionic build

#script to be run such as tests

before_script:
  - echo "no tests"

script:
  - docker --version #print docker version
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend waqasnoor/udagram-frontend:latest
  - docker tag udagram-frontend waqasnoor/udagram-frontend:"$TRAVIS_BUILD_NUMBER"

# Tasks to perform after image
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push waqasnoor/udagram-frontend:"$TRAVIS_BUILD_NUMBER"
  - docker push waqasnoor/udagram-frontend:latest
